name: Continuous Integration
on: [push]
jobs:
  static-check:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn install
      - run: yarn lint:all

  type-check:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn install
      - run: yarn typecheck

  jest-tests:
    if: always()
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ["."]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn install
      - name: Run unit and integration tests
        working-directory: ${{ matrix.project }}
        run: yarn test

  # e2e-tests:
  #   if: always()
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       project: [".", "./examples/amaranth-demo", "./examples/advanced-demo"]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '18'
  #         cache: 'yarn'
  #     - run: yarn install
  #     - name: Run E2E tests
  #       uses: cypress-io/github-action@v4.1.0
  #       with:
  #         working-directory: ${{ matrix.project }}
  #         build: yarn build
  #         start: yarn serve
  #         browser: chrome
  #       env:
  #         CYPRESS_SUPPORT: "y"
